version: '3.4'

services:
  urban-octo-computing-machine:
    image: urbanoctocomputingmachine:dev
    build:
      target: base
    environment:
      - NUGET_PACKAGES=C:\.nuget\packages
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_urban-octo-computing-machine$
    volumes:
      - C:\git\Source\Repos\urban-octo-computing-machine\urban-octo-computing-machine:C:\app
      - C:\Users\keith\onecoremsvsmon:C:\remote_debugger:ro
#$nuget_volume_mapping_urban-octo-computing-machine$
    entrypoint: cmd /c "set DISABLE_PERFORMANCE_DEBUGGER=1 & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_urban-octo-computing-machine$ bin\\Debug\\netcoreapp2.1\\urban-octo-computing-machine.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"